version: '3.5'

x-services-volume:
  &php-volume
  type: bind
  source: ./php
  target: /php
 
services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        working_dir: /php
        volumes:
            - <<: *php-volume
            - ./logs:/var/log/php
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        container_name: php-fpm
        networks:
            - app_net
    nginx:
        image: nginx:1.17-alpine
        depends_on:
        - php
        ports:
        - 10090:80
        volumes:
        - *php-volume
        - ./logs:/var/log/nginx
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        container_name: nginx_latest
        networks:
            - app_net
networks:
    app_net:
        driver: "bridge"
volumes:
    db-store:
